version: '3.8'

services:
  broker:
    build: ./broker
    ports:
      - "5000:5000"
    volumes:
      - broker-data:/app/data
    networks:
      - minimq-network

  producer-cpu:
    build: ./producer
    depends_on:
      - broker
    networks:
      - minimq-network
    restart: unless-stopped
    environment:
      - METRIC_TYPE=cpu

  producer-mem:
    build: ./producer
    depends_on:
      - broker
    networks:
      - minimq-network
    restart: unless-stopped
    environment:
      - METRIC_TYPE=mem

  producer-disk:
    build: ./producer
    depends_on:
      - broker
    networks:
      - minimq-network
    restart: unless-stopped
    environment:
      - METRIC_TYPE=disk

  consumer:
    build: ./consumer
    ports:
      - "8080:8080"
    depends_on:
      - broker
    networks:
      - minimq-network

volumes:
  broker-data:

networks:
  minimq-network:
    driver: bridge
