apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  namespace: minimq

spec:
  replicas: 1
  selector:
    matchLabels: 
      app: broker
  template:
    metadata:
      labels: 
        app: broker

    spec:
      containers: 
      - name: broker
        image: lui5da/broker:latest
        ports:
        - containerPort: 5000


---      

apiVersion: v1
kind: Service
metadata: 
  name: broker
  namespace: minimq

spec: 
  selector:
    app: broker

  ports:
  - port: 5000
    targetPort: 5000
  
  type: ClusterIP




